#!/bin/bash

module purge
module load python/2.7.11
module load python/2.7.11-matplotlib

PKG_NAME="payu"
PKG_VERSION="test"
FORCE="y"

# System Environment
BASEDIR="/short/${PROJECT}/${USER}/payulib"
PROJECT_MODULEFILES="${BASEDIR}/modules"
PROJECT_APPS="${BASEDIR}/apps"

AUTHOR_UID=$(whoami)
MOD_AUTHOR=$(getent passwd ${AUTHOR_UID} | cut -d: -f5)
MOD_EMAIL=$(ldapsearch -LLL -x "(uid=${AUTHOR_UID})" mail | \
            grep -oP "(?<=mail: ).*$")

# Get package version (or use a custom version)
if [[ ! -n ${PKG_VERSION} ]]; then
    PKG_VERSION=$(python -c "print(__import__('${PKG_NAME}').__version__)")
fi

# Get application paths
PKG_ROOT="${PROJECT_APPS}/${PKG_NAME}/${PKG_VERSION}"
PKG_BIN="${PKG_ROOT}/bin"
PKG_LIB="${PKG_ROOT}/lib"

# Check if application is already installed
if [[ -d ${PKG_ROOT} && ! -n ${FORCE} ]]; then
    echo "There is already an application installed at ${PKG_ROOT}."
    exit -1
fi

rm -rf ${PKG_ROOT}
mkdir -p ${PKG_BIN}
mkdir -p ${PKG_LIB}

# TODO: Set source directory
python setup.py install_lib --install-dir ${PKG_LIB}
python setup.py install_scripts --install-dir ${PKG_BIN}

# Install dependencies
# pip install --no-cache-dir -t ${PKG_LIB} f90nml
# pip install --no-cache-dir -t ${PKG_LIB} pyyaml
# pip install --no-cache-dir -t ${PKG_LIB} requests[security]
# pip install --no-cache-dir -t ${PKG_LIB} yamanifest
if [ -z "" ]; then
pip install -t ${PKG_LIB} f90nml
pip install -t ${PKG_LIB} pyyaml
pip install -t ${PKG_LIB} requests[security]
pip install -t ${PKG_LIB} yamanifest
# pip install -t ${PKG_LIB} pathos
fi

# Generate the modulefile
PKG_APP_MODS=${PROJECT_MODULEFILES}/${PKG_NAME}
mkdir -p ${PKG_APP_MODS}

PKG_MOD=${PKG_APP_MODS}/${PKG_VERSION}
printf "#%%Module1.0\n" > ${PKG_MOD}
printf "# ${PKG_NAME} ${PKG_VERSION} environment module\n" >> ${PKG_MOD}
printf "\n" >> ${PKG_MOD}
printf "set install-contact \"${MOD_AUTHOR} <${MOD_EMAIL}>\"\n" >> ${PKG_MOD}
printf "set install-date \"$(date +%Y-%m-%d)\"\n" >> ${PKG_MOD}
printf "source /opt/Modules/extensions/extensions.tcl\n" >> ${PKG_MOD}
printf "docommon\n" >> ${PKG_MOD}

## Update default version
#printf "#%%Module1.0\n" > ${PKG_APP_MODS}/.version
#printf "set ModulesVersion ${PKG_VERSION}\n" >> ${PKG_APP_MODS}/.version

# Set permissions
chmod g=rX ${PROJECT_APPS}/${PKG_NAME}
chmod o=rX ${PROJECT_APPS}/${PKG_NAME}

chmod -R g=rX ${PKG_ROOT}
chmod -R o=rX ${PKG_ROOT}

chmod g=rX ${PKG_APP_MODS}
chmod o=rX ${PKG_APP_MODS}

chmod g=rX ${PKG_MOD}
chmod o=rX ${PKG_MOD}


